version: '3'

services:
  web:
    build: .
    command: python manage.py runsslserver 0.0.0.0:443 --certificate /path/to/certificate.crt --key /path/to/private.key
    volumes:
      - .:/app
      - /path/to/certificate.crt:/path/to/certificate.crt
      - /path/to/private.key:/path/to/private.key
    ports:
      - "443:443"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: labconnect
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootadmin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
