version: '3'

services:
  web:
    build: .
    command: python manage.py runsslserver 0.0.0.0:443 --certificate /app/certificado.crt --key /app/chave_privada.key
    volumes:
      - .:/app
      - /etc/ssl/certs/certificado.crt:/app/certificado.crt
      - /etc/ssl/private/chave_privada.key:/app/chave_privada.key
    ports:
      - "443:443"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: labconnect
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootadmin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
