# Generated by Django 5.0.3 on 2024-04-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_disciplina_laboratorio_turma_agenda'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('laboratorio', 'data_agendada', 'horario_agendado')},
        ),
    ]
