name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: SSH para a Máquina EC2
        uses: appleboy/ssh-action@master
        with:
          host: 3.137.174.9
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd LabConnect
            chmod +x deploy.sh
            ./deploy.sh
